---
- name: installing packages
  hosts: all
  gather_facts: yes
  become: true
  
  tasks:
  - name: installing httpd Redhat
    yum:
      name: httpd
      state: installed
    notify: start httpd services
    
    
  - name: Copy file with owner and permissions
    copy:
     src: /home/ansadmin/playbooks/index.html
     dest: /var/www/html
    
    
  handlers:
  - name: start httpd services
    service:
      name: httpd
      state: started
    



/*

---
- name: installing packages
  hosts: all
  gather_facts: yes
  become: true

  tasks:
    - name: installing httpd on Redhat
      yum:
        name: httpd
        state: installed
      when: ansible_os_family == "Redhat"
      notify: start httpd services

    - name: installing httpd on Ubuntu
      apt:
        name: apache2
        state: present
      when: ansible_os_family == "Debian"

     - name: Copy file with owner and permissions
      copy:
        src: /home/ansadmin/playbooks/index.html
        dest: /var/www/html

    - name: starting httpd services
      service:
        name: httpd
        state: started
      when: ansible_os_family == "Redhat"

    - name: starting apache services
      service:
        name: apache2
        state: started
      when: ansible_os_family == "Debian"

  


*/