---
- name: installing packages
  hosts: all
  gather_facts: yes
  become: true
  
  tasks:
  - name: installing httpd Redhat
    yum:
      name: httpd
      state: installed
    notify: start httpd services
    
    
 - name: Copy file with owner and permissions
    copy:
     src: /home/ansadmin/playbooks/index.html
     dest: /var/www/html
    
    
  handlers:
  - name: start httpd services
    service:
      name: httpd
      state: started
    
