---
- name: uninstalling packages
  hosts: all
  gather_facts: no
  become: true
  
  tasks:
  - name: uninstalling httpd packages
    yum:
      name: httpd
      state: absent
    when: ansible_os_family == "RedHat"
     
       
   - name: remove apache2 packages
     apt:
       name: apache2
       state: absent
    when: ansible_os_family == "Debian"
     
    
