---
- name: uninstall multiple packages
  hosts: all
  gather_facts: yes
  become: true
  
  tasks:
  - name: uninstal packages
    yum:
      name: "{{item.package}}"
      state: "{{item.setup}}"
    loop:
      - {package: 'git', setup: 'installed'}
      - {package: 'make', setup: 'latest'}
      - {package: 'wget', setup: 'removed'}
      - {package: 'tree', setup: 'absent'}
   